Refactor
GO-SHIP-Oceanography/station_bathymetry pull request #5
Opened 2023-10-27 20:48 UTC by jatkinson1000

Tidying of the code in the jupyter notebook:

- [x] Apply black
- [x] Convert to using f-strings
- [x] Make lat/lon limits variables
- [ ] Refactor so all parameters set in one cell
- [ ] Standardise data location
- [ ] Automatically download bathymetry data file

2023-11-01 16:26 UTC, lcimoli requested changes
Thanks!

2023-11-01 16:26 UTC, lcimoli commented on plot_bathymetry_at_station.ipynb
> +    "* `station_we_are_at` - Integer number of the current measuring station (see output of cell 3 or track file)\n",
duplicate line - to remove

2023-11-01 16:26 UTC, lcimoli commented on plot_bathymetry_at_station.ipynb
> +    "Example data is provided in `./resources/` but if you have a general location for cruise data files amend it to this.\n",
./resources folder does not exists yet (hence code does not run). Add trackfile in resources as well.

2023-11-01 16:26 UTC, lcimoli commented on plot_bathymetry_at_station.ipynb
> +    "if high_res:\n",
High res download does not work (link gives 404 error)

2023-11-01 16:26 UTC, lcimoli commented on plot_bathymetry_at_station.ipynb
> +    "    topo_name = \"SRTM15_v2.5.nc\"  # High-res topology file to use\n",
Topology should be "topography" (here and in other parts of the code/comments)

2023-11-01 16:26 UTC, lcimoli commented on plot_bathymetry_at_station.ipynb
> +    "   NOTE: The code can attempt to download this data if it cannot find it, but note that the files are large, especially the high-resolution version (6GB), so it is advised tpo do this in advance
tpo --> to

2023-11-01 17:46 UTC, jatkinson1000 commented on plot_bathymetry_at_station.ipynb
> +    "   NOTE: The code can attempt to download this data if it cannot find it, but note that the files are large, especially the high-resolution version (6GB), so it is advised tpo do this in advance
Fixed.

2023-11-01 17:46 UTC, jatkinson1000 commented on plot_bathymetry_at_station.ipynb
> +    "    topo_name = \"SRTM15_v2.5.nc\"  # High-res topology file to use\n",
Fixed.

2023-11-01 17:47 UTC, jatkinson1000 commented on plot_bathymetry_at_station.ipynb
> +    "if high_res:\n",
The issue was a lower case v instead of an upper case V in the file name. I also bumped the file from V2.5 to V2.5.5

2023-11-01 17:47 UTC, jatkinson1000 commented on plot_bathymetry_at_station.ipynb
> +    "Example data is provided in `./resources/` but if you have a general location for cruise data files amend it to this.\n",
Fixed in latest commit fb17617

2023-11-01 17:47 UTC, jatkinson1000 commented on plot_bathymetry_at_station.ipynb
> +    "* `station_we_are_at` - Integer number of the current measuring station (see output of cell 3 or track file)\n",
Fixed

2023-11-03 14:10 UTC, lcimoli approved these changes

2023-11-03 14:10 UTC, merged